ktor:
    application:
        modules:
            - br.com.expert.ApplicationKt.module
    deployment:
        port: 8080

db:
  mongo:
    user: ${?DB_MONGO_USER}
    password: ${?DB_MONGO_PASSWORD}
    database:
      name: "nutricao_db"
